name: "Index Content"
on:
  push:
    # paths:
    # - 'content/**'

jobs:
  hello-actions:
    name: Hello, Actions!
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Print the message.
        env:
          MESSAGE: Hello, Actions

        run: |
          echo $MESSAGE!
