name: "Index Content"
on:
  push:
    # paths:
    # - 'content/**'

jobs:
  index-content:
    name: index-content
    runs-on: ubuntu-18.04

    steps:
      - name: checkout.
        uses: actions/checkout@v2

      - name: Build the main index.
        run:  find ./content/ -type f | jq -R -s -c 'split("\n")|.[0:-1]' | tee index/main.json

      - name: Print git status.
        run:  git status
