name: "Index Content"
on:
  push:
    # paths:
    # - 'content/**'

jobs:
  print-content:
    name: Hello, Actions!
    runs-on: ubuntu-18.04

    steps:
      - name: checkout.
        uses: actions/checkout@v2

      - name: Print the message.
        env:
          MESSAGE: Hello, Actions
        run: |
          find ./content
