name: Publish Github Proxy Worker

on:
  push:
    branches:
      - '**'

    paths:
      - '**'
      - .cloudflare/**
      - .github/workflows/publish-worker.yml

jobs:
  publish-workers:
    name:    Publish Github Proxy Worker
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Worker
        uses: actions/checkout@v2

      - name: Delete Existing Worker
        run: 'curl -X DELETE https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/scripts/$SCRIPT_NAME -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"'

        env:
          SCRIPT_NAME: github-proxy

      - name: Publish GithubProxy Worker
        uses: cloudflare/wrangler-action@1.2.0

      - name: Delete Existing KV Store
        run: cd .cloudflare/workers/github-proxy && yes | wrangler kv:namespace delete --namespace-id=`wrangler kv:namespace list | jq -r '.[] | select(.title == "${SCRIPT_NAME}-kv").id'`
        working-directory: '.cloudflare/workers/github-proxy'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          SCRIPT_NAME: github-proxy

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Init, Plan, Deploy
        run:  terraform init . && terraform plan . && terraform apply --auto-approve .
        working-directory: ./cloudflare/workers/${SCRIPT_NAME}


      # - name: Publish GithubAuth Worker
      #   uses: cloudflare/wrangler-action@1.2.0
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     workingDirectory: '.cloudflare/workers/github-auth'
