name: Publish Github Proxy Worker

on:
  push:
    branches:
      - '**'

    paths:
      - '**'
      # - .cloudflare/**
      # - .github/workflows/publish-worker.yml

jobs:
  publish-workers:
    name:    Publish Github Proxy Worker
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Worker
        uses: actions/checkout@v2

      - name: Delete Existing Worker
        run: 'curl -X DELETE https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/workers/scripts/$SCRIPT_NAME -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"'
        env:
          SCRIPT_NAME: github-proxy

      - name: Delete Existing KV Store
        run: sudo npm i -g @cloudflare/wrangler && yes | wrangler kv:namespace delete --namespace-id=`wrangler kv:namespace list | jq -r '.[] | select(.title == "${SCRIPT_NAME}-kv").id'` || true
        working-directory: '.cloudflare/workers/github-proxy'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SCRIPT_NAME: github-proxy

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Init, Plan, Deploy
        run:  curl -fsSL https://apt.releases.hashicorp.com/gpg
        working-directory: ./cloudflare/workers/${SCRIPT_NAME}


      # - name: Publish GithubAuth Worker
      #   uses: cloudflare/wrangler-action@1.2.0
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     workingDirectory: '.cloudflare/workers/github-auth'
